### ISSUE TITLE
start local server

### ISSUE THREAD

**Issue by carljmosca** [Tenacity-Dev/vite-react-ts-tailwind-tanstack-query-eslint-prettier#1]
Excellent work, thank you for creating and sharing it.  It appears that the `npm run web` should be `npm run dev` to start the server.

**Comment by Tenacity-Dev** [comment]
Check the `package.json` file. It is `npm run dev`

**Comment by carljmosca** [comment]
Right, that's what I tried to say above.  Was just trying to get you to fix the README.md file in case someone did not know that.

<img width="261" alt="Screenshot 2024-03-21 at 7 44 45 PM" src="https://github.com/Tenacity-Dev/vite-react-ts-tailwind-tanstack-query-eslint-prettier/assets/215651/155bb3c8-4bf4-479f-b8cc-c8d4cac12120">
